version: "3.9"
services:
    iudxdashboard:
        image: registry.gitlab.com/scrc-iiit/website/iudxdashboard
        networks:
            - nginx-proxy-server
        restart: always

networks:
    nginx-proxy-server:
        external: true
